title: 'Steve Dower'
description: 'Musings and Mutterings'

plugins:
  - jekyll-redirect-from

lsi: false
safe: true
source: .
incremental: false
excerpt_separator: '<!--more-->'
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-slate

collections:
  posts:
    output: true
    permalink: /blog/:slug
    is_root: false
  pages:
    output: true
    is_root: false
  research:
    sort_by: sort_key
    output: true
    permalink: /research/:slug
    is_root: false
